# Generated by Django 4.2.11 on 2024-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='renewal_options',
            field=models.BooleanField(default=True),
        ),
    ]
