# Generated by Django 4.2.11 on 2024-04-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_lease_renewal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='month',
            field=models.IntegerField(),
        ),
    ]
